# Generated by Django 5.2.7 on 2025-10-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('price', models.CharField(blank=True, max_length=128)),
                ('price_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('agent', models.CharField(blank=True, max_length=255)),
                ('listing_url', models.URLField(max_length=1000, unique=True)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
