# Generated by Django 5.2.7 on 2025-10-22 15:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('listing_url', models.URLField(max_length=1000, unique=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('agent_phone', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.CharField(blank=True, max_length=128)),
                ('price_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('bedrooms', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('bathrooms', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('size', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('key_features', models.JSONField(blank=True, default=list)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('scraping_status', models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scraping_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['external_id'], name='scraper_pro_externa_d89566_idx'), models.Index(fields=['price_numeric'], name='scraper_pro_price_n_c9ff21_idx'), models.Index(fields=['bedrooms'], name='scraper_pro_bedroom_744293_idx'), models.Index(fields=['property_type'], name='scraper_pro_propert_ac62d5_idx'), models.Index(fields=['scraped_at'], name='scraper_pro_scraped_9c38fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('image_title', models.CharField(blank=True, max_length=200)),
                ('image_order', models.IntegerField(default=0, help_text="Order of image in the property's image list")),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary/main image')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scraper.propertylisting')),
            ],
            options={
                'ordering': ['image_order', 'scraped_at'],
                'indexes': [models.Index(fields=['property', 'image_order'], name='scraper_pro_propert_c4d852_idx'), models.Index(fields=['is_primary'], name='scraper_pro_is_prim_116d9f_idx')],
                'unique_together': {('property', 'image_url')},
            },
        ),
    ]
