# Generated by Django 5.2.7 on 2025-10-21 16:03

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertylisting',
            options={'ordering': ['-scraped_at']},
        ),
        migrations.RenameField(
            model_name='propertylisting',
            old_name='agent',
            new_name='agent_name',
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='accessibility',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='agent_address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='agent_logo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='coordinates_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='coordinates_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='council_tax',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='date_reduced',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='epc_rating',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='epc_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='floorplan_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='garden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_balcony',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_concierge',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_garage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_garden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_gym',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_parking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_pool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='is_reduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='key_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='parking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='price_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='property_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='rights_restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='scraping_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='scraping_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='tenure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='utilities_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='video_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='virtual_tour_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['external_id'], name='scraper_pro_externa_d89566_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['price_numeric'], name='scraper_pro_price_n_c9ff21_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['bedrooms'], name='scraper_pro_bedroom_744293_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['property_type'], name='scraper_pro_propert_ac62d5_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['scraped_at'], name='scraper_pro_scraped_9c38fd_idx'),
        ),
    ]
