# Generated by Django 5.2.7 on 2025-10-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_remove_propertylisting_accessibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='image_urls',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('image_title', models.CharField(blank=True, max_length=200)),
                ('image_order', models.IntegerField(default=0, help_text="Order of image in the property's image list")),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary/main image')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scraper.propertylisting')),
            ],
            options={
                'ordering': ['image_order', 'scraped_at'],
                'indexes': [models.Index(fields=['property', 'image_order'], name='scraper_pro_propert_c4d852_idx'), models.Index(fields=['is_primary'], name='scraper_pro_is_prim_116d9f_idx')],
                'unique_together': {('property', 'image_url')},
            },
        ),
    ]
