# Generated by Django 5.2.7 on 2025-10-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_remove_propertylisting_image_urls_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
