# Generated by Django 5.2.7 on 2025-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_propertylisting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
