# Generated by Django 5.2.7 on 2025-10-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_propertylisting_agent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='agent_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
