# Generated by Django 5.2.7 on 2025-10-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_alter_propertylisting_agent_phone'),
    ]

    operations = [
    ]
